### ISSUE TITLE
Pandoc.brew not producing table of contents

### ISSUE THREAD

**Issue by carlganz** [Rapporter/pander#214]
Hello Pander team,

I have a very simply .brew file, that works as I expect when I use the old brew function, but with Pandoc.brew the .tex file has an empty table of contents, and I get warnings saying "pander.return is deprecated. Use 'pander_return' instead." 

It's a pretty short .brew file so I'll just paste it here:

```\documentclass[oneside]{article}
\headsep=10pt
\usepackage[margin=2cm]{geometry}
\usepackage[pdftex]{graphicx}
\usepackage{subfig}
\usepackage{graphicx}
\usepackage{float}
\usepackage{verbatim}
\usepackage{fancyhdr}
\usepackage{hyperref}
\hypersetup{
  colorlinks=true,
  pdfauthor={Carl}
}

\graphicspath{{./graphs/}}

\title{Data Dictionary}
\author{Cars}
\date{\today}
\raggedbottom
\setcounter{tocdepth}{1}

\pagestyle{fancy}
\fancyhf{}
\rhead{Cars}
\lhead{Carl}
\rfoot{Page \thepage}
\begin{document}

\maketitle

This is a data dictionary for Cars dataset

\tableofcontents

<% library(xtable); %>

<% procfreq<-function(x) {
  #find frequencies
  temp<-as.data.frame(table(x))
  #generate percents
  temp[,3]<-temp[,2]/sum(temp[,2])
  #name columns
  names(temp)<-c("Values","Frequencies","Percent")
  return(temp)
} %>
  
  <% for (i in seq_along(names(mtcars))) { -%>
  \pagebreak
  
  
<%= cat("\\section{\\uppercase{",names(mtcars)[i],"}}",sep="") %>

Here is where the labels and other information will go: \\

  <% tmp <- xtable(procfreq(mtcars[,i]),names(mtcars)[i],names(mtcars)[i]) %>
  <% print(tmp) %>
  
  \clearpage
<% } -%>
  
\end{document}
```
If I understand correctly, Pandoc.brew should be able to do anything brew does, so I presume the discrepancy here is a bug. I'm just letting you guys know in case this is a bug.

My session info:
```
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] lattice_0.20-33 xtable_1.7-4   
[3] pander_0.5.2    brew_1.0-6     
[5] foreign_0.8-65  ggplot2_1.0.1  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.0      digest_0.6.8    
 [3] MASS_7.3-40      grid_3.2.1      
 [5] plyr_1.8.3       gtable_0.1.2    
 [7] magrittr_1.5     scales_0.2.5    
 [9] stringi_0.5-5    reshape2_1.4.1  
[11] proto_0.3-10     tools_3.2.1     
[13] stringr_1.0.0    munsell_0.4.2   
[15] colorspace_1.2-6
```

Regards,
Carl Ganz

**Comment by daroczig** [comment]
`Pandoc.brew` is a modified version of `brew` -- with some differences. First of all, it is intended to use markdown as much as possible, and you do not need to `cat` the R objects/messages, but all R objects in the code chunks are automatically passed to `pander` to transform the object to markdown. Thus, no need to call `xtable` -- although it works fine if your required output format is PDF.

About your example:
* I think the `documentclass` is missing
* the ToC is empty because the `\section` LaTeX commands are not rendered in the TeX file -- please try removing the `cat` calls and feel free to have the static parts of the command outside of the R chunk, something like this:

```
\section{\uppercase{<%= names(mtcars)[i] %>}}
```

* no need to `print` (and `xtable`) the tabular objects, you can simply return a `data.frame` or similar object in any `<%= ... %>` chunk

Based on the above, I'd provide the following more `pander`-like alternative solution for the example:

```
This is a data dictionary for Cars dataset

<% for (v in names(mtcars)) { %>
\pagebreak

## <%= v %>

Here is where the labels and other information will go:

<%= rapportools::rp.freq(v, mtcars) %>
\clearpage

<% } %>
```

Rendering to PDF right away via:

```r
Pandoc.brew('filename.brew', output = tempfile(), convert = 'pdf')
```

**Comment by carlganz** [comment]
Thank you Gergely for your help here as well as for your help over on Stackoverflow. As you may have noticed, I am just learning how to use Pander, but so far I am extremely impressed.

Regards

**Comment by daroczig** [comment]
Happy yo help, @carlganz, and thanks for your kind words.
